### ISSUE TITLE
Using routing instead of _routing in bulk request

### ISSUE THREAD

**Issue by dynaxis** [whitfin/elasticsearch-bulk-operator#1]
Since ES 6.x, ES spits out warnings saying the following:

```
[2018-03-28 03:07:20.997] [WARN ][I/O dispatcher 2] | o.e.c.RequestLogger.logResponse [65] - request
[POST http://192.168.0.169:9200/_bulk] returned 2 warnings: [299 Elasticsearch-6.2.3-c59ff00 
"Deprecated field [_routing] used, expected [routing] instead" "Tue, 27 Mar 2018 18:07:08 GMT"],[299 
Elasticsearch-6.2.3-c59ff00 "Deprecated field [_routing] used, expected [routing] instead" "Tue, 27 Mar 
2018 18:07:20 GMT"]
```
It would be good if we can have another version supporting Elasticsearch 6.x.

**Comment by whitfin** [comment]
@dynaxis want to PR the changes? Are there any other deprecations?

**Comment by dynaxis** [comment]
According to the current [Elasticsearch reference](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html), only the following 3 were changed:

* `_version` -> `version`
* `_routing` -> `routing`
* `_version_type` -> `version_type`: this is irrelevant since `BulkAction` doesn't support it.

And fortunately, Elasticsearch 5.0 and later seem to work fine both with or without `_` (Low level Rest client was introduced in 5.0).

This is a very simple change. So if you still want me to issue a PR, then please comment here. I'll issue one.

Thanks.

**Comment by whitfin** [comment]
@dynaxis I'll have this in later today, thanks for reporting!

**Comment by whitfin** [comment]
@dynaxis I've checked this in (on your word that it works with 5.0 still). I also added support for `version_type`, since there's no reason that shouldn't be supported. Once CI builds, I'll push to central as 1.0.3 :)

**Comment by dynaxis** [comment]
Thanks for your effort. This project saved me a lot of time.
